# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookFood' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookFood

  target 'BookFoodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookFoodUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod ‘Firebase/Auth’
  
  pod 'Moltin', :git => 'https://github.com/moltin/ios-sdk.git', :branch => 'master'
  pod 'SDWebImage', '~>3.7'

end
